# Generated by Django 5.2.4 on 2025-07-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_email_subscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="attachment",
            field=models.FileField(blank=True, upload_to="email_attachments/"),
        ),
    ]
