# Generated by Django 5.2.4 on 2025-07-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataentry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Customer_name", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=20)),
            ],
        ),
    ]
