# Generated by Django 5.2.4 on 2025-07-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataentry", "0002_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="Customer_name",
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_name",
            field=models.CharField(default="Unknown", max_length=20),
        ),
    ]
